"""baseline: tender_opportunity + tender_cpv

Revision ID: 8f81000f2f85
Revises: 
Create Date: 2026-05-30 22:29:10.032938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8f81000f2f85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_opportunity',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_notice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_region_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_region_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_value_eur', sa.Float(), nullable=True),
    sa.Column('fx_rate_date', sa.DateTime(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline_tz_offset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notice_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_type_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('award_supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender_opportunity', schema=None) as batch_op:
        batch_op.create_index('ix_tender_buyer_country', ['buyer_country'], unique=False)
        batch_op.create_index('ix_tender_deadline', ['deadline'], unique=False)
        batch_op.create_index('ix_tender_estimated_value', ['estimated_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_opportunity_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index('ix_tender_source', ['source'], unique=False)
        batch_op.create_index('ix_tender_status', ['status'], unique=False)

    op.create_table('tender_cpv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpv_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpv_division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender_cpv', schema=None) as batch_op:
        batch_op.create_index('ix_tender_cpv_code', ['cpv_code'], unique=False)
        batch_op.create_index('ix_tender_cpv_division', ['cpv_division'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_cpv_tender_id'), ['tender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_cpv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_cpv_tender_id'))
        batch_op.drop_index('ix_tender_cpv_division')
        batch_op.drop_index('ix_tender_cpv_code')

    op.drop_table('tender_cpv')
    with op.batch_alter_table('tender_opportunity', schema=None) as batch_op:
        batch_op.drop_index('ix_tender_status')
        batch_op.drop_index('ix_tender_source')
        batch_op.drop_index(batch_op.f('ix_tender_opportunity_buyer_id'))
        batch_op.drop_index('ix_tender_estimated_value')
        batch_op.drop_index('ix_tender_deadline')
        batch_op.drop_index('ix_tender_buyer_country')

    op.drop_table('tender_opportunity')
    # ### end Alembic commands ###
